### ISSUE TITLE
"Boundary (singular) fit" with non-overlapping batch

### ISSUE THREAD

**Issue by robbwh** [jcbeer/longCombat#3]
Hello, 

I am implementing longcombat on some data to account for scanner/software upgrades. 

lme4 is able to converge when I exclude the last batch:

![image](https://user-images.githubusercontent.com/39274562/159833242-2624a4a3-d6e8-4844-8f3c-c6a22b4950d1.png)

Like so:

![image](https://user-images.githubusercontent.com/39274562/159833305-c6e8f4bc-3cab-4589-92e4-6712d1675108.png)

But when longcombat without excluding that batch, I get an error about lme4 convergence on all but feature 2:

Image of convergence failures:
<img width="540" alt="Screen Shot 2022-03-23 at 10 01 08 PM" src="https://user-images.githubusercontent.com/39274562/159833516-2c92140e-958f-4a1e-b634-5b2fa81d6e29.png">

When I exclude the batch without overlap, I don't see those messages:

<img width="656" alt="Screen Shot 2022-03-23 at 10 02 26 PM" src="https://user-images.githubusercontent.com/39274562/159833603-c537c9ad-1533-4a5a-9398-6cfb136f7416.png">

Are there any lme4 settings I can tinker with in the package, or will it likely not work due to non-overlapping batches?

Thank you

**Comment by jcbeer** [comment]
Hello!
Thanks for the question.
Looks like it is working ok for feature 2.
That error often means that one of the random effects has a variance
parameter that is very close to zero or the model is overfitted in other
ways.
What does your model look like? Maybe you could drop one of the random
effects?
I assume you are using a continuous/numeric time variable. Do you have any
time-squared in the model? If so you could try dropping the squared term.
To get a better idea of what is happening, I would suggest fitting the
model with a batch fixed effect and looking at the output with summary() to
see where you might be having large standard errors or random effect
variance parameters close to zero.
Sometimes that error occurs but the estimates are still reasonable...
Joanne
