### ISSUE TITLE
Doubts in longCombat package

### ISSUE THREAD

**Issue by Jingzcode** [jcbeer/longCombat#6]
Dear Dr. Beer,

Thank you very much for sharing this package and I’m writing this email about section 4.3 in your paper (Beer et al., 2020). 

In section 4.3, ‘restricted case’ and ‘general case’ are compared. And in the supplementary file, I also found Figure S33A which compares the unharmonized and harmonized data for these two cases using ‘longCombat’. I would like to ask **how the ‘restricted case’ get harmonized** in this paper since there is **no scanner batch effect** in this case and at least one batch effect is required in ‘longCombat’ package. 

Due to the design of our project, we only have 10 subjects with repeated 2 scans each subject in one scanner and another different 10 subjects repeat 2 scans in another scanner. We would like to explore consistency after harmonization at the individual level. I suppose this situation belongs to the ‘restricted case’ but I couldn’t find how to apply ‘longCombat’ package in this case. I would appreciate it very much if you could give any suggestions. 

Thank you very much for your time and hope you have a nice day!

 Best regards
Janet

**Comment by jcbeer** [comment]
Hi Janet, thanks for your question.

For the 'restricted case' you mention, there is actually a scanner batch
effect. 'Restricted case' refers to the situation where participants are
each only scanned (repeatedly) on a single scanner, but there are multiple
scanners and they have associated scanner effects on the mean and variance.
This does sound like it applies to your design.

Your design is balanced, which is good as you will have the same
statistical power for measuring both sets of scanner effects. I'm not sure
what exactly you mean by "explore consistency after harmonization at the
individual level." In any case, there are no special procedures you need to
do to apply longCombat to your data; you can apply it in the usual way.

I would suggest making sure your samples are well balanced across the two
scanners. The best case scenario would be if they were randomized to
different scanners. If not, then you will definitely want to include
covariates in your model such as age, sex, biological status (treatment,
disease status, whatever is being studied). (I would suggest including
these covariates even if they were randomized.)

Let me know if you have further questions & good luck with the study.

Sincerely, Joanne

**Comment by Jingzcode** [comment]
Dear Dr. Beer,


Thank you so much for your kind reply and suggestions.

I'm sorry for the unclear explanation about "explore consistency after harmonization at the individual level" in the last email. Actually, we would like to explore the intra-scanner variation as well as try to harmonize this intra-scanner variation (the variation between the first and second scan within the same scanner & same participant).  

I'm a little bit confused with the 'associated scanner effects on mean and variance'. If I understand correctly, LongCombat harmonization could be helpful to decrease the within-subject variability and scanner effect. So I tried to apply LongCombat in our study (similar to 'restricted cases') and compare the ICC (before vs after LongCombat). However, I found the ICC between 1st and 2nd scan haven't significantly improved (some even become worse). 

Thanks again for sharing this amazing package and paper. I would appreciate it very much if you could give any suggestions.


Best regards
Janet

**Comment by jcbeer** [comment]
Hi Janet,

Ok I see. So you expect there to be no biological differences between the
first and second scans? If that is actually the case, then you could try
making the second set of scans on each scanner into their own "batch."

The goal of ComBat / longitudinal ComBat is to remove technical variation
but retain any biological variation, so yes it should decrease scanner
effect, and might decrease within-subject variability but it depends
whether the true biological variation is in the same or the opposite
direction of the scanner effect.

Did you include a "timepoint" fixed effect in the model (to indicate first
vs second scans)? That would tend to retain the differences in mean between
the two scans, so you could leave that out.

I would suggest to include a subject random intercept, and maybe try making
the second set of scans into its own batch for each scanner, so you would
have 4 batches of scans and ComBat will harmonize means and variances
across those. I imagine this should decrease ICC.

Joanne

**Comment by Jingzcode** [comment]
Dear Dr. Beer,

Thanks a lot for your help. Wish you a happy new year!

Best regards
Janet
